### ISSUE TITLE
Caused by: java.net.URISyntaxException: Illegal character when retrieving user list from user view

### ISSUE THREAD

**Issue by jonesbusy** [pingunaut/nexus3-crowd-plugin#67]
Hello,

Actually we are unable to retrieve the full user list from the user views. It seems some of our user ID are using some invalid character for URL (Perhaps # or @)

Tested with Nexus 3.15 OSS and version 3.5.0 of the plugin

(name + URL where anonymized)

`java.lang.IllegalArgumentException: Illegal character in fragment at index 133: https://mydomain.url/rest/usermanagement/1/user/group/nested?username=foobar#ext#@my.domainname
at java.net.URI.create(URI.java:852)
at org.apache.http.client.methods.HttpGet.<init>(HttpGet.java:66)
at com.pingunaut.nexus3.crowd.plugin.internal.CachingNexusCrowdClient.httpGet(CachingNexusCrowdClient.java:93)
at com.pingunaut.nexus3.crowd.plugin.internal.CachingNexusCrowdClient.findRolesByUser(CachingNexusCrowdClient.java:163)
at com.pingunaut.nexus3.crowd.plugin.internal.CrowdUserManager.completeUserRolesAndSource(CrowdUserManager.java:66)
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1556)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
....`

Let me know if you need more details.

Regards,

**Comment by pingunaut** [comment]
Thanks a lot for your patience. This is fixed with [nexus3-crowd-plugin-3.6.0](https://github.com/pingunaut/nexus3-crowd-plugin/releases/tag/nexus3-crowd-plugin-3.6.0)
