### ISSUE TITLE
It seams like Crow return XML and not JSON

### ISSUE THREAD

**Issue by pranasblk** [pingunaut/nexus3-crowd-plugin#83]
First of all thanks for the maintaining the plug-in!

I have set-up issue and may need your advices.

**_Environment:_**
-  Atlassian Crowd Version: 3.3.4 
- Sonatype Nexus Repository Manager: OSS 3.23.0-03 (docker image)
-  nexus3-crowd-plugin: 3.8.1

Adding Crowd Authenticatio Realm is ok, but attempt to retrieve group causes parsing errors:

`nexus3_1 | 2020-06-11 11:04:50,457+1000 INFO  [qtp827108577-57] admin com.pingunaut.nexus3.crowd.plugin.CrowdAuthenticatingRealm - doGetAuthorizationInfo for admin
nexus3_1 | 2020-06-11 11:04:50,514+1000 ERROR [qtp827108577-57] admin com.pingunaut.nexus3.crowd.plugin.internal.entity.mapper.CrowdMapper - Error while mapping result
nexus3_1 | com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
nexus3_1 | 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:200)
nexus3_1 | 	at com.google.gson.Gson.fromJson(Gson.java:810)
nexus3_1 | 	at com.google.gson.Gson.fromJson(Gson.java:775)
nexus3_1 | 	at com.google.gson.Gson.fromJson(Gson.java:724)
nexus3_1 | 	at com.google.gson.Gson.fromJson(Gson.java:696)
nexus3_1 | 	at com.pingunaut.nexus3.crowd.plugin.internal.entity.mapper.CrowdMapper.toRoleStrings(CrowdMapper.java:68)
nexus3_1 | 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:223)
nexus3_1 | 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:191)
nexus3_1 | 	at com.pingunaut.nexus3.crowd.plugin.internal.CachingNexusCrowdClient.executeQuery(CachingNexusCrowdClient.java:86)
nexus3_1 | 	at com.pingunaut.nexus3.crowd.plugin.internal.CachingNexusCrowdClient.findRolesByUser(CachingNexusCrowdClient.java:164)
nexus3_1 | 	at com.pingunaut.nexus3.crowd.plugin.CrowdAuthenticatingRealm.doGetAuthorizationInfo(CrowdAuthenticatingRealm.java:76)
nexus3_1 | 	at org.apache.shiro.realm.AuthorizingRealm.getAuthorizationInfo(AuthorizingRealm.java:341)
nexus3_1 | 	at org.apache.shiro.realm.AuthorizingRealm.isPermitted(AuthorizingRealm.java:488)
nexus3_1 | 	at org.sonatype.nexus.security.authz.ExceptionCatchingModularRealmAuthorizer.isPermitted(ExceptionCatchingModularRealmAuthorizer.java:256)
nexus3_1 | 	at org.apache.shiro.mgt.AuthorizingSecurityManager.isPermitted(AuthorizingSecurityManager.java:125)
nexus3_1 | 	at org.apache.shiro.subject.support.DelegatingSubject.isPermitted(DelegatingSubject.java:179)
nexus3_1 | 	at org.sonatype.nexus.security.SecurityHelper.isPermitted(SecurityHelper.java:201)
nexus3_1 | 	at org.sonatype.nexus.repository.security.RepositoryPermissionChecker.userHasPermission(RepositoryPermissionChecker.java:180)
nexus3_1 | 	at org.sonatype.nexus.repository.security.RepositoryPermissionChecker.userCanBrowseRepositories(RepositoryPermissionChecker.java:94)
nexus3_1 | 	at org.sonatype.nexus.repository.security.RepositoryPermissionChecker.userCanBrowseRepositories(RepositoryPermissionChecker.java:136)
nexus3_1 | 	at org.sonatype.nexus.repository.security.RepositoryPermissionChecker$userCanBrowseRepositories.call(Unknown Source)
nexus3_1 | 	at org.sonatype.nexus.coreui.RepositoryComponent.getBrowseableFormats(RepositoryComponent.groovy:137)
nexus3_1 | 	at org.sonatype.nexus.coreui.RepositoryComponent$$EnhancerByGuice$$2adc479b.CGLIB$getBrowseableFormats$14(<generated>)
nexus3_1 | 	at org.sonatype.nexus.coreui.RepositoryComponent$$EnhancerByGuice$$2adc479b$$FastClassByGuice$$1fac23fa.invoke(<generated>)
nexus3_1 | 	at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
nexus3_1 | 	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:76)
nexus3_1 | 	at com.palominolabs.metrics.guice.ExceptionMeteredInterceptor.invoke(ExceptionMeteredInterceptor.java:23)
nexus3_1 | 	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:77)
nexus3_1 | 	at com.palominolabs.metrics.guice.TimedInterceptor.invoke(TimedInterceptor.java:26)
nexus3_1 | 	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:77)
nexus3_1 | 	at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:55)
nexus3_1 | 	at org.sonatype.nexus.coreui.RepositoryComponent$$EnhancerByGuice$$2adc479b.getBrowseableFormats(<generated>)
nexus3_1 | 	at org.sonatype.nexus.coreui.RepositoryComponent.getState(RepositoryComponent.groovy:149)
nexus3_1 | 	at org.sonatype.nexus.rapture.internal.state.StateComponent.getState(StateComponent.java:87)
nexus3_1 | 	at org.sonatype.nexus.rapture.internal.state.StateComponent$$EnhancerByGuice$$c680be9.CGLIB$getState$0(<generated>)
nexus3_1 | 	at org.sonatype.nexus.rapture.internal.state.StateComponent$$EnhancerByGuice$$c680be9$$FastClassByGuice$$f5589e80.invoke(<generated>)
nexus3_1 | 	at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
nexus3_1 | 	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:76)
nexus3_1 | 	at com.palominolabs.metrics.guice.ExceptionMeteredInterceptor.invoke(ExceptionMeteredInterceptor.java:23)
nexus3_1 | 	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:77)
nexus3_1 | 	at com.palominolabs.metrics.guice.TimedInterceptor.invoke(TimedInterceptor.java:26)
nexus3_1 | 	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:77)
nexus3_1 | 	at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:55)
nexus3_1 | 	at org.sonatype.nexus.rapture.internal.state.StateComponent$$EnhancerByGuice$$c680be9.getState(<generated>)
nexus3_1 | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
nexus3_1 | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
nexus3_1 | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
nexus3_1 | 	at java.lang.reflect.Method.invoke(Method.java:498)
nexus3_1 | 	at com.softwarementors.extjs.djn.router.dispatcher.DispatcherBase.invokeJavaMethod(DispatcherBase.java:142)
nexus3_1 | 	at com.softwarementors.extjs.djn.router.dispatcher.DispatcherBase.invokeMethod(DispatcherBase.java:133)
nexus3_1 | 	at org.sonatype.nexus.extdirect.internal.ExtDirectDispatcher.invokeMethod(ExtDirectDispatcher.java:82)
nexus3_1 | 	at com.softwarementors.extjs.djn.router.dispatcher.DispatcherBase.dispatch(DispatcherBase.java:63)
nexus3_1 | 	at com.softwarementors.extjs.djn.router.processor.poll.PollRequestProcessor.process(PollRequestProcessor.java:145)
nexus3_1 | 	at org.sonatype.nexus.extdirect.internal.ExtDirectServlet$3.processPollRequest(ExtDirectServlet.java:262)
nexus3_1 | 	at com.softwarementors.extjs.djn.servlet.DirectJNgineServlet.processRequest(DirectJNgineServlet.java:636)
nexus3_1 | 	at com.softwarementors.extjs.djn.servlet.DirectJNgineServlet.doPost(DirectJNgineServlet.java:595)
nexus3_1 | 	at org.sonatype.nexus.extdirect.internal.ExtDirectServlet.doPost(ExtDirectServlet.java:137)
nexus3_1 | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
nexus3_1 | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
nexus3_1 | 	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286)
nexus3_1 | 	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276)
nexus3_1 | 	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181)
nexus3_1 | 	at com.google.inject.servlet.DynamicServletPipeline.service(DynamicServletPipeline.java:71)
nexus3_1 | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
nexus3_1 | 	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:112)
nexus3_1 | 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
nexus3_1 | 	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
nexus3_1 | 	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
nexus3_1 | 	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
nexus3_1 | 	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
nexus3_1 | 	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
nexus3_1 | 	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
nexus3_1 | 	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
nexus3_1 | 	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
nexus3_1 | 	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
nexus3_1 | 	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
nexus3_1 | 	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
nexus3_1 | 	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
nexus3_1 | 	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
nexus3_1 | 	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
nexus3_1 | 	at org.sonatype.nexus.security.SecurityFilter.executeChain(SecurityFilter.java:85)
nexus3_1 | 	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
nexus3_1 | 	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
nexus3_1 | 	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
nexus3_1 | 	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387)
nexus3_1 | 	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
nexus3_1 | 	at org.sonatype.nexus.security.SecurityFilter.doFilterInternal(SecurityFilter.java:101)
nexus3_1 | 	at 
...
nexus3_1 | Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
nexus3_1 | 	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:387)
nexus3_1 | 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:189)
nexus3_1 | 	... 134 common frames omitted
`

Do you have some ideas on further set-up digging?

Thanks!

**Comment by pranasblk** [comment]
wrong path of crowd it had /applications suffix
